- name: ensure supervisor is installed
  pip: name=supervisor state=present
  sudo: yes

- name: ensure supervisor config folder exists
  file: path={{ supervisor_config_dir }} state=directory
  sudo: yes

- name: set supervisord config
  template: src=supervisord.conf.j2 dest={{ supervisor_config_dir }}/supervisord.conf
  sudo: yes

- name: ensure supervisor apps config folder exists
  file: path={{ supervisor_apps_config_dir }} state=directory
  sudo: yes

- name: set supervisor programs config
  template: src={{ supervisor_program_config }}
            dest={{ supervisor_apps_config_dir }}/{{ item.name }}.conf
  with_items: programs
  sudo: yes

- name: set supervisord init config
  template: src=supervisord.init.j2 dest=/etc/init.d/supervisord mode=0755
  sudo: yes

- name: add supervisord to init
  command: update-rc.d supervisord defaults
  sudo: yes

- name: ensure supervisord is started
  service: name=supervisord state=started
  sudo: yes

- name: reread supervisor app
  supervisorctl: name={{ item.name }} state=present
  with_items: programs
  sudo: yes

- name: update supervisor app
  supervisorctl: name={{ item.name }} state=restarted
  with_items: programs
  sudo: yes
